### ISSUE TITLE
extra semicolon in jinja template

### ISSUE THREAD

**Issue by zpe-diegor** [ZPESystems/Ansible#35]
https://github.com/ZPESystems/Ansible/blob/d97ddc5d1f0166665fcd2929a9cd2de8fb51a7f8/collections/ansible_collections/zpe/nodegrid/roles/network_wg_site_to_site/templates/wireguard-failover.sh.j2#L15C1-L16C13

instead of 
```
      ;;
{% endfor %}
```
should be

```
{% endfor %}
      ;;
```

@zpe-reneneumann @zpe-diegom

**Comment by zpe-diegom** [comment]
Fix on develop branch.
