### ISSUE TITLE
Add support for manage_devices_permissions to sec_authorization.yml

### ISSUE THREAD

**Issue by zpe-reneneumann** [ZPESystems/Ansible#36]
We need to add support for the following permissions in case that `manage_devices_permissions` is set to `yes`

These options need to be added to 

collections/ansible_collections/zpe/nodegrid/roles/system_authentication/tasks/sec_authorization.yml

Options:
manage_devices_general_settings = yes
manage_devices_connection_settings = yes
manage_devices_inbound_access_settings = yes
manage_devices_management = yes
manage_devices_logging = yes
manage_devices_custom_fields = yes
manage_devices_commands = yes
manage_devices_outlets = yes
manage_devices_sensor_channels = yes

**Comment by zpe-diegom** [comment]
Fix on develop branch.
